version: '3'

services:
  php:
    container_name: laravel_project_php
    build: 
      context: ./php
      args:
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}

  nginx:
    image: nginx
    container_name: laravel_project_nginx
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - php

  postgres:
    image: postgres
    container_name: laravel_project_postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
#      - ./postgres/init.d:/docker-entrypoint-initdb.d
      - ./postgres/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4
    container_name: laravel_project_pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin/storage
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres